/**
 * Club registry helpers. Wire into UI when ready.
 * Data file is generated by scripts/build_clubs.py
 */
import { CLUBS, type Club } from '@/data/clubs'

const byCode = new Map<string, Club>(CLUBS.map((club) => [club.code, club]))

export type { Club }
export { CLUBS }

export function getClubByCode(code: string | null | undefined): Club | undefined {
  if (!code) return undefined
  return byCode.get(code)
}

export function getClubDisplayName(code: string | null | undefined): string {
  const club = getClubByCode(code)
  if (club?.name) return club.name
  return code ?? ''
}

export function getClubLogoUrl(code: string | null | undefined): string | undefined {
  return getClubByCode(code)?.logoUrl
}
