// AUTO-GENERATED by scripts/build_clubs.py. Do not edit by hand.
// Generated: 2026-06-04T02:52:37Z
// Seasons scanned: 2024, 2025, 2026
// Clubs: 449 (431 with display name)

export type Club = {
  code: string
  name: string | null
  logoUrl: string
}

export const CLUBS: readonly Club[] = [
  {
      "code": "ABHS",
      "name": "Auburn HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ABHS.png"
    },
    {
      "code": "ABPC",
      "name": "Albert Park College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ABPC.png"
    },
    {
      "code": "ABSP",
      "name": "Auburn South PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ABSP.png"
    },
    {
      "code": "ACT",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ACT.png"
    },
    {
      "code": "AKSC",
      "name": "Akira SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/AKSC.png"
    },
    {
      "code": "ALB",
      "name": "Albury",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ALB.png"
    },
    {
      "code": "ALBA",
      "name": "ALB / Albury LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ALBA.png"
    },
    {
      "code": "ALMC",
      "name": "Alamanda College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ALMC.png"
    },
    {
      "code": "ALXS",
      "name": "Alexandra SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ALXS.png"
    },
    {
      "code": "ANQ",
      "name": "Athletics North Qld",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ANQ.png"
    },
    {
      "code": "ANW",
      "name": "Nunawading",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ANW.png"
    },
    {
      "code": "APS",
      "name": "APS United",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/APS.png"
    },
    {
      "code": "APTG",
      "name": "Alphington GS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/APTG.png"
    },
    {
      "code": "AQUC",
      "name": "Aquinas College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/AQUC.png"
    },
    {
      "code": "ASPC",
      "name": "Assumption College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ASPC.png"
    },
    {
      "code": "ASW",
      "name": "Athletics South West",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ASW.png"
    },
    {
      "code": "ATHL",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ATHL.png"
    },
    {
      "code": "ATKC",
      "name": "Aitken College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ATKC.png"
    },
    {
      "code": "AV",
      "name": "Club AV",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/AV.png"
    },
    {
      "code": "AVLC",
      "name": "Avila College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/AVLC.png"
    },
    {
      "code": "AVMC",
      "name": "Ave Maria College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/AVMC.png"
    },
    {
      "code": "AWA",
      "name": "Waverley",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/AWA.png"
    },
    {
      "code": "BALG",
      "name": "Ballarat Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BALG.png"
    },
    {
      "code": "BALH",
      "name": "Ballarat High",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BALH.png"
    },
    {
      "code": "BAR",
      "name": "Ballarat Region",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BAR.png"
    },
    {
      "code": "BBNH",
      "name": "Blackburn HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BBNH.png"
    },
    {
      "code": "BCHC",
      "name": "Beaconhills College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BCHC.png"
    },
    {
      "code": "BCLC",
      "name": "Ballarat Clarendon College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BCLC.png"
    },
    {
      "code": "BCMG",
      "name": "Bacchus Marsh Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BCMG.png"
    },
    {
      "code": "BCPS",
      "name": "Berwick Chase PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BCPS.png"
    },
    {
      "code": "BDGS",
      "name": "Bendigo SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BDGS.png"
    },
    {
      "code": "BDSC",
      "name": "Bairnsdale SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BDSC.png"
    },
    {
      "code": "BEL",
      "name": "Bellarine",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BEL.png"
    },
    {
      "code": "BER",
      "name": "Bendigo Region",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BER.png"
    },
    {
      "code": "BEU",
      "name": "Bendigo Uni",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BEU.png"
    },
    {
      "code": "BGO",
      "name": "Bendigo Harriers",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BGO.png"
    },
    {
      "code": "BHA",
      "name": "Ballarat Harriers",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BHA.png"
    },
    {
      "code": "BHCS",
      "name": "Belgrave Heights CS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BHCS.png"
    },
    {
      "code": "BILC",
      "name": "Billanook College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BILC.png"
    },
    {
      "code": "BLCG",
      "name": "Balcombe Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BLCG.png"
    },
    {
      "code": "BLMH",
      "name": "Belmont HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BLMH.png"
    },
    {
      "code": "BLWH",
      "name": "Balwyn High",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BLWH.png"
    },
    {
      "code": "BNBP",
      "name": "Bonbeach PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BNBP.png"
    },
    {
      "code": "BNTS",
      "name": "Bentleigh SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BNTS.png"
    },
    {
      "code": "BOH",
      "name": "Box Hill",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BOH.png"
    },
    {
      "code": "BOXH",
      "name": "Box Hill HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BOXH.png"
    },
    {
      "code": "BOXS",
      "name": "Box Hill Senior SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BOXS.png"
    },
    {
      "code": "BPKS",
      "name": "Buckley Park SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BPKS.png"
    },
    {
      "code": "BRIG",
      "name": "Brighton Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BRIG.png"
    },
    {
      "code": "BRIS",
      "name": "Brighton SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BRIS.png"
    },
    {
      "code": "BRMC",
      "name": "Braemar College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BRMC.png"
    },
    {
      "code": "BSEC",
      "name": "Bendigo South East",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BSEC.png"
    },
    {
      "code": "BSWS",
      "name": "Brunswick SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BSWS.png"
    },
    {
      "code": "BTWS",
      "name": "Brentwood SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BTWS.png"
    },
    {
      "code": "BWK",
      "name": "Brunswick",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BWK.png"
    },
    {
      "code": "BYBC",
      "name": "Braybrook College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BYBC.png"
    },
    {
      "code": "BYC",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BYC.png"
    },
    {
      "code": "BYCB",
      "name": "Ballarat YCW AV / Ballarat LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BYCB.png"
    },
    {
      "code": "BYCS",
      "name": "Bindjiroo Yaluk",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/BYCS.png"
    },
    {
      "code": "CARG",
      "name": "Carey Baptist Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CARG.png"
    },
    {
      "code": "CAUG",
      "name": "Caulfield Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CAUG.png"
    },
    {
      "code": "CBAG",
      "name": "Cobram Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CBAG.png"
    },
    {
      "code": "CBES",
      "name": "Cranbourne East SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CBES.png"
    },
    {
      "code": "CBGS",
      "name": "Canterbury Girls SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CBGS.png"
    },
    {
      "code": "CBWH",
      "name": "Camberwell HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CBWH.png"
    },
    {
      "code": "CBWS",
      "name": "Cranbourne West SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CBWS.png"
    },
    {
      "code": "CCA",
      "name": "Casey Cardinia",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CCA.png"
    },
    {
      "code": "CCCC",
      "name": "Caroline Chisholm CC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CCCC.png"
    },
    {
      "code": "CCR",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CCR.png"
    },
    {
      "code": "CGBS",
      "name": "Craigieburn SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CGBS.png"
    },
    {
      "code": "CHCS",
      "name": "Chairo Christian School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CHCS.png"
    },
    {
      "code": "CHI",
      "name": "Chilwell",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CHI.png"
    },
    {
      "code": "CHL",
      "name": "Chile",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CHL.png"
    },
    {
      "code": "CHRC",
      "name": "Christian College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CHRC.png"
    },
    {
      "code": "CHWC",
      "name": "Christway College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CHWC.png"
    },
    {
      "code": "CLBP",
      "name": "Columba Catholic PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CLBP.png"
    },
    {
      "code": "CLDC",
      "name": "Catholic Ladies College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CLDC.png"
    },
    {
      "code": "CLDS",
      "name": "Clyde SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CLDS.png"
    },
    {
      "code": "CLNC",
      "name": "Clonard College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CLNC.png"
    },
    {
      "code": "CLPP",
      "name": "Cairnlea Park PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CLPP.png"
    },
    {
      "code": "CLWC",
      "name": "Cathedral College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CLWC.png"
    },
    {
      "code": "CMAC",
      "name": "Catherine McAuley College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CMAC.png"
    },
    {
      "code": "CNHC",
      "name": "Cornish College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CNHC.png"
    },
    {
      "code": "COB",
      "name": "Coburg",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/COB.png"
    },
    {
      "code": "COBH",
      "name": "Coburg High School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/COBH.png"
    },
    {
      "code": "COL",
      "name": "Collingwood",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/COL.png"
    },
    {
      "code": "COR",
      "name": "Corio",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/COR.png"
    },
    {
      "code": "CRCC",
      "name": "CRC Caroline Springs",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CRCC.png"
    },
    {
      "code": "CRCR",
      "name": "Crosbie Crew",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CRCR.png"
    },
    {
      "code": "CRMP",
      "name": "Carrum PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CRMP.png"
    },
    {
      "code": "CRSC",
      "name": "Crusoe College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CRSC.png"
    },
    {
      "code": "CRWH",
      "name": "Corowa HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CRWH.png"
    },
    {
      "code": "CSTE",
      "name": "Crest Education",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CSTE.png"
    },
    {
      "code": "CSYG",
      "name": "Casey Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CSYG.png"
    },
    {
      "code": "CTEP",
      "name": "Cheltenham East PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CTEP.png"
    },
    {
      "code": "CTHS",
      "name": "Cheltenham SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CTHS.png"
    },
    {
      "code": "CTSP",
      "name": "Clayton South PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CTSP.png"
    },
    {
      "code": "CVNC",
      "name": "Covenant College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CVNC.png"
    },
    {
      "code": "CWGG",
      "name": "Camberwell Girls Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CWGG.png"
    },
    {
      "code": "CWGS",
      "name": "Camberwell Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/CWGS.png"
    },
    {
      "code": "DAC",
      "name": "Doncaster",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DAC.png"
    },
    {
      "code": "DACK",
      "name": "DAC / Knox LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DACK.png"
    },
    {
      "code": "DIV",
      "name": "Diamond Valley",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DIV.png"
    },
    {
      "code": "DIVC",
      "name": "Diamond Valley College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DIVC.png"
    },
    {
      "code": "DIVD",
      "name": "DIV / Doncaster",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DIVD.png"
    },
    {
      "code": "DKN",
      "name": "Deakin",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DKN.png"
    },
    {
      "code": "DLSC",
      "name": "De La Salle College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DLSC.png"
    },
    {
      "code": "DMNC",
      "name": "Dromana College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DMNC.png"
    },
    {
      "code": "DMSC",
      "name": "Damascus College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DMSC.png"
    },
    {
      "code": "DNTR",
      "name": "Dandenongs Trail Runners",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DNTR.png"
    },
    {
      "code": "DON",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DON.png"
    },
    {
      "code": "DPDP",
      "name": "Deepdene PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DPDP.png"
    },
    {
      "code": "DRNS",
      "name": "Drouin SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DRNS.png"
    },
    {
      "code": "DSA",
      "name": "Dandenong-Springvale",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DSA.png"
    },
    {
      "code": "DVCC",
      "name": "Donvale Christian",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/DVCC.png"
    },
    {
      "code": "EAG",
      "name": "Eaglehawk",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EAG.png"
    },
    {
      "code": "EBMC",
      "name": "Elisabeth Murdoch College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EBMC.png"
    },
    {
      "code": "ECH",
      "name": "Echuca Moama",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ECH.png"
    },
    {
      "code": "EDBC",
      "name": "Edinburgh College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EDBC.png"
    },
    {
      "code": "EDBS",
      "name": "Edenbrook SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EDBS.png"
    },
    {
      "code": "EDCS",
      "name": "East Doncaster SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EDCS.png"
    },
    {
      "code": "EKA",
      "name": "Eureka",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EKA.png"
    },
    {
      "code": "EKAB",
      "name": "EKA / Ballarat LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EKAB.png"
    },
    {
      "code": "ELTH",
      "name": "Eltham HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ELTH.png"
    },
    {
      "code": "ELWC",
      "name": "Elwood College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ELWC.png"
    },
    {
      "code": "EMA",
      "name": "Echuca Moama",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EMA.png"
    },
    {
      "code": "EMER",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EMER.png"
    },
    {
      "code": "EMES",
      "name": "Emerson School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EMES.png"
    },
    {
      "code": "EMNC",
      "name": "Emmanuel College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EMNC.png"
    },
    {
      "code": "EMRS",
      "name": "Emerald SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EMRS.png"
    },
    {
      "code": "EMWC",
      "name": "Emmanuel College Warrnambool",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/EMWC.png"
    },
    {
      "code": "ESC",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ESC.png"
    },
    {
      "code": "ESS",
      "name": "Essendon",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/ESS.png"
    },
    {
      "code": "FAC",
      "name": "Frankston",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/FAC.png"
    },
    {
      "code": "FBKG",
      "name": "Firbank Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/FBKG.png"
    },
    {
      "code": "FCYH",
      "name": "Footscray HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/FCYH.png"
    },
    {
      "code": "FKN",
      "name": "Frankston",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/FKN.png"
    },
    {
      "code": "FLCC",
      "name": "Flinders Christian College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/FLCC.png"
    },
    {
      "code": "FRNH",
      "name": "Frankston HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/FRNH.png"
    },
    {
      "code": "FTGS",
      "name": "Fintona GS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/FTGS.png"
    },
    {
      "code": "GBR",
      "name": "Great Britain",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GBR.png"
    },
    {
      "code": "GBVG",
      "name": "Goulburn Valley Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GBVG.png"
    },
    {
      "code": "GEEG",
      "name": "Geelong Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GEEG.png"
    },
    {
      "code": "GELC",
      "name": "Geelong Lutheran College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GELC.png"
    },
    {
      "code": "GENZ",
      "name": "Genazzano College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GENZ.png"
    },
    {
      "code": "GER",
      "name": "Geelong Region",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GER.png"
    },
    {
      "code": "GFDT",
      "name": "Goldfield Trail Runners",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GFDT.png"
    },
    {
      "code": "GFTR",
      "name": "Goldfields RC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GFTR.png"
    },
    {
      "code": "GHY",
      "name": "Glenhuntly",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GHY.png"
    },
    {
      "code": "GHYA",
      "name": "GHY",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GHYA.png"
    },
    {
      "code": "GHYC",
      "name": "GHY / Camberwell Mal",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GHYC.png"
    },
    {
      "code": "GHYM",
      "name": "GHY / Moorabbin LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GHYM.png"
    },
    {
      "code": "GHYS",
      "name": "GHY / Sandringham LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GHYS.png"
    },
    {
      "code": "GIPG",
      "name": "Gippsland Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GIPG.png"
    },
    {
      "code": "GIRG",
      "name": "Girton Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GIRG.png"
    },
    {
      "code": "GLCC",
      "name": "Galen Catholic College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GLCC.png"
    },
    {
      "code": "GLES",
      "name": "Gleneagles SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GLES.png"
    },
    {
      "code": "GLG",
      "name": "Geelong Guild",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GLG.png"
    },
    {
      "code": "GLWS",
      "name": "Glen Waverley SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GLWS.png"
    },
    {
      "code": "GNEC",
      "name": "Glen Eira College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GNEC.png"
    },
    {
      "code": "GNLC",
      "name": "Good News Lutheran College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GNLC.png"
    },
    {
      "code": "GPA",
      "name": "Gippsland",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GPA.png"
    },
    {
      "code": "GPKS",
      "name": "Gladstone Park SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GPKS.png"
    },
    {
      "code": "GRBS",
      "name": "Greensborough SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GRBS.png"
    },
    {
      "code": "GRSS",
      "name": "Greater Shepparton SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GRSS.png"
    },
    {
      "code": "GSNS",
      "name": "Gisborne SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GSNS.png"
    },
    {
      "code": "GVDS",
      "name": "Grovedale SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/GVDS.png"
    },
    {
      "code": "HALG",
      "name": "Hume Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HALG.png"
    },
    {
      "code": "HBRC",
      "name": "Hobsons Bay RC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HBRC.png"
    },
    {
      "code": "HBYC",
      "name": "Haileybury College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HBYC.png"
    },
    {
      "code": "HBYG",
      "name": "Haileybury Girls College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HBYG.png"
    },
    {
      "code": "HDCC",
      "name": "Heathdale Christian College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HDCC.png"
    },
    {
      "code": "HMGT",
      "name": "Holmesglen",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HMGT.png"
    },
    {
      "code": "HMTP",
      "name": "Hampton Primary School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HMTP.png"
    },
    {
      "code": "HSHC",
      "name": "Horsham College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HSHC.png"
    },
    {
      "code": "HSTP",
      "name": "Holy Spirit PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HSTP.png"
    },
    {
      "code": "HTWS",
      "name": "Huntingtower School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HTWS.png"
    },
    {
      "code": "HVES",
      "name": "Highvale SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HVES.png"
    },
    {
      "code": "HZGC",
      "name": "Hazel Glen college",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/HZGC.png"
    },
    {
      "code": "IAV",
      "name": "Independent AV",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/IAV.png"
    },
    {
      "code": "IN2",
      "name": "Independent",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/IN2.png"
    },
    {
      "code": "IVA",
      "name": "Ivanhoe",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/IVA.png"
    },
    {
      "code": "IVGG",
      "name": "Ivanhoe Girls Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/IVGG.png"
    },
    {
      "code": "IVHG",
      "name": "Ivanhoe Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/IVHG.png"
    },
    {
      "code": "JMCP",
      "name": "James Cook PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/JMCP.png"
    },
    {
      "code": "JMSS",
      "name": "John Monash Science School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/JMSS.png"
    },
    {
      "code": "JNIP",
      "name": "Juniper College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/JNIP.png"
    },
    {
      "code": "JNPC",
      "name": "John Paul College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/JNPC.png"
    },
    {
      "code": "JPN",
      "name": "Japan",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/JPN.png"
    },
    {
      "code": "KBRC",
      "name": "Kilbreda College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KBRC.png"
    },
    {
      "code": "KBYC",
      "name": "Kambrya College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KBYC.png"
    },
    {
      "code": "KEWH",
      "name": "Kew HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KEWH.png"
    },
    {
      "code": "KIE",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KIE.png"
    },
    {
      "code": "KLAS",
      "name": "Kalianna Secondary School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KLAS.png"
    },
    {
      "code": "KLDC",
      "name": "Keilor Downs College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KLDC.png"
    },
    {
      "code": "KNA",
      "name": "Knox",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KNA.png"
    },
    {
      "code": "KNAK",
      "name": "KNA / Knox LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KNAK.png"
    },
    {
      "code": "KNAS",
      "name": "KNA / Sherbrooke LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KNAS.png"
    },
    {
      "code": "KNGS",
      "name": "Koonung SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KNGS.png"
    },
    {
      "code": "KNIC",
      "name": "Kardinia International",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KNIC.png"
    },
    {
      "code": "KRNC",
      "name": "Kurnai College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KRNC.png"
    },
    {
      "code": "KSB",
      "name": "Keilor St Bernards",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KSB.png"
    },
    {
      "code": "KVTG",
      "name": "Kilvington Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KVTG.png"
    },
    {
      "code": "KYGP",
      "name": "Kunyung PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/KYGP.png"
    },
    {
      "code": "LAL",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LAL.png"
    },
    {
      "code": "LCB",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LCB.png"
    },
    {
      "code": "LHAG",
      "name": "Lowther Hall Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LHAG.png"
    },
    {
      "code": "LLDH",
      "name": "Lilydale HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LLDH.png"
    },
    {
      "code": "LMHL",
      "name": "Loreto Mandeville",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LMHL.png"
    },
    {
      "code": "LNGS",
      "name": "Leongatha SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LNGS.png"
    },
    {
      "code": "LOYC",
      "name": "Loyola College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LOYC.png"
    },
    {
      "code": "LTCB",
      "name": "Loreto Ballarat",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LTCB.png"
    },
    {
      "code": "LTHC",
      "name": "Luther College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LTHC.png"
    },
    {
      "code": "LVCC",
      "name": "Lavalla Catholic College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LVCC.png"
    },
    {
      "code": "LVTR",
      "name": "Love the Run",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LVTR.png"
    },
    {
      "code": "LWNC",
      "name": "Lowanna College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LWNC.png"
    },
    {
      "code": "LWRC",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/LWRC.png"
    },
    {
      "code": "MAAG",
      "name": "Moama Anglican Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MAAG.png"
    },
    {
      "code": "MAC",
      "name": "Maccabi",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MAC.png"
    },
    {
      "code": "MAL",
      "name": "Malvern",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MAL.png"
    },
    {
      "code": "MBNP",
      "name": "Mirboo North PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MBNP.png"
    },
    {
      "code": "MBYC",
      "name": "Maribyrnong College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MBYC.png"
    },
    {
      "code": "MBYS",
      "name": "Mount Beauty SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MBYS.png"
    },
    {
      "code": "MDRC",
      "name": "Mad Rabit Crew",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MDRC.png"
    },
    {
      "code": "MEN",
      "name": "Mentone",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MEN.png"
    },
    {
      "code": "MENA",
      "name": "MEN",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MENA.png"
    },
    {
      "code": "MENC",
      "name": "MEN / Chelsea LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MENC.png"
    },
    {
      "code": "MENM",
      "name": "Men / Mentone LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MENM.png"
    },
    {
      "code": "MFD",
      "name": "Mansfield",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MFD.png"
    },
    {
      "code": "MFGS",
      "name": "Matthew Flinders Girls SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MFGS.png"
    },
    {
      "code": "MKNS",
      "name": "McKinnon SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MKNS.png"
    },
    {
      "code": "MLBG",
      "name": "Melbourne Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MLBG.png"
    },
    {
      "code": "MLDC",
      "name": "Mcclelland College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MLDC.png"
    },
    {
      "code": "MLGC",
      "name": "Melbourne Girls College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MLGC.png"
    },
    {
      "code": "MLGG",
      "name": "Melbourne Girls Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MLGG.png"
    },
    {
      "code": "MLHS",
      "name": "Melbourne HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MLHS.png"
    },
    {
      "code": "MLMC",
      "name": "Mount Lilydale Mercy",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MLMC.png"
    },
    {
      "code": "MLTS",
      "name": "Melton SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MLTS.png"
    },
    {
      "code": "MLVP",
      "name": "Malvern PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MLVP.png"
    },
    {
      "code": "MMCC",
      "name": "Marymede Cath College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MMCC.png"
    },
    {
      "code": "MMDM",
      "name": "Melbourne Midday Milers",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MMDM.png"
    },
    {
      "code": "MMYS",
      "name": "Montmorency SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MMYS.png"
    },
    {
      "code": "MNTG",
      "name": "Mentone Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MNTG.png"
    },
    {
      "code": "MNVC",
      "name": "monivae college",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MNVC.png"
    },
    {
      "code": "MORC",
      "name": "Mordialloc College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MORC.png"
    },
    {
      "code": "MORS",
      "name": "Mornington SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MORS.png"
    },
    {
      "code": "MPA",
      "name": "Mornington",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MPA.png"
    },
    {
      "code": "MPAF",
      "name": "MPA / Frankston LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MPAF.png"
    },
    {
      "code": "MRBC",
      "name": "Mad Rabbit Crew",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MRBC.png"
    },
    {
      "code": "MRBS",
      "name": "Mooroolbark SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MRBS.png"
    },
    {
      "code": "MRCB",
      "name": "Marist College Bendigo",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MRCB.png"
    },
    {
      "code": "MRCN",
      "name": "Marcellin College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MRCN.png"
    },
    {
      "code": "MRGH",
      "name": "MacRobertson Girls HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MRGH.png"
    },
    {
      "code": "MRNT",
      "name": "Maranatha Christian School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MRNT.png"
    },
    {
      "code": "MRSC",
      "name": "Marist Sion College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MRSC.png"
    },
    {
      "code": "MRYI",
      "name": "Mary Immaculate",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MRYI.png"
    },
    {
      "code": "MTAC",
      "name": "Mount Alexander College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MTAC.png"
    },
    {
      "code": "MTCC",
      "name": "Mater Christi",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MTCC.png"
    },
    {
      "code": "MTES",
      "name": "Mount Eliza Secondary",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MTES.png"
    },
    {
      "code": "MTGG",
      "name": "Mentone Girls' Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MTGG.png"
    },
    {
      "code": "MTGS",
      "name": "Mentone Girls SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MTGS.png"
    },
    {
      "code": "MTLC",
      "name": "Methodist Ladies College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MTLC.png"
    },
    {
      "code": "MTRS",
      "name": "Mount Rowan SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MTRS.png"
    },
    {
      "code": "MTSP",
      "name": "Mount Scopus",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MTSP.png"
    },
    {
      "code": "MUU",
      "name": "Melbourne Uni",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MUU.png"
    },
    {
      "code": "MWVS",
      "name": "Mount Waverley SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MWVS.png"
    },
    {
      "code": "MYBE",
      "name": "Maryborough Education",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MYBE.png"
    },
    {
      "code": "MZNC",
      "name": "Mazenod College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/MZNC.png"
    },
    {
      "code": "NAGC",
      "name": "Nagle College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NAGC.png"
    },
    {
      "code": "NCTH",
      "name": "Northcote HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NCTH.png"
    },
    {
      "code": "NDMC",
      "name": "Notre Dame College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NDMC.png"
    },
    {
      "code": "NER",
      "name": "North East Region",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NER.png"
    },
    {
      "code": "NEWH",
      "name": "Newhaven College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NEWH.png"
    },
    {
      "code": "NGES",
      "name": "North Geelong Secondary Colleg",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NGES.png"
    },
    {
      "code": "NMBP",
      "name": "North Melbourne PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NMBP.png"
    },
    {
      "code": "NPGP",
      "name": "Newport Gardens PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NPGP.png"
    },
    {
      "code": "NRWS",
      "name": "Narre Warren South P12",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NRWS.png"
    },
    {
      "code": "NSLH",
      "name": "Nossal HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NSLH.png"
    },
    {
      "code": "NSW",
      "name": "New South Wales",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NSW.png"
    },
    {
      "code": "NTAS",
      "name": "Nathalia SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NTAS.png"
    },
    {
      "code": "NWDS",
      "name": "Norwood SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NWDS.png"
    },
    {
      "code": "NZCP",
      "name": "Nazareth Catholic PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NZCP.png"
    },
    {
      "code": "NZL",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/NZL.png"
    },
    {
      "code": "OBRH",
      "name": "Oberon HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OBRH.png"
    },
    {
      "code": "OFRS",
      "name": "Officer SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OFRS.png"
    },
    {
      "code": "OLHC",
      "name": "Our Lady Help of Christians",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OLHC.png"
    },
    {
      "code": "OLM",
      "name": "Old Melburnians",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OLM.png"
    },
    {
      "code": "OLMC",
      "name": "Our Lady of Mercy",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OLMC.png"
    },
    {
      "code": "OLPP",
      "name": "Our Lady of the Pines",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OLPP.png"
    },
    {
      "code": "OLSC",
      "name": "Our Lady of Sion",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OLSC.png"
    },
    {
      "code": "OLSH",
      "name": "Our Lady of Sacred Heart",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OLSH.png"
    },
    {
      "code": "OLX",
      "name": "Old Xaverians",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OLX.png"
    },
    {
      "code": "OSC",
      "name": "Old Scotch",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OSC.png"
    },
    {
      "code": "OSCB",
      "name": "OSC / Box Hill LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OSCB.png"
    },
    {
      "code": "OSPS",
      "name": "Officer Specialist",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OSPS.png"
    },
    {
      "code": "OVNC",
      "name": "Overnewton College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OVNC.png"
    },
    {
      "code": "OXCC",
      "name": "Oxley Christian",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/OXCC.png"
    },
    {
      "code": "PBLC",
      "name": "Presbyterian Ladies' College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PBLC.png"
    },
    {
      "code": "PDAC",
      "name": "Padua College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PDAC.png"
    },
    {
      "code": "PEGS",
      "name": "Penleigh Essendon",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PEGS.png"
    },
    {
      "code": "PENG",
      "name": "Peninsula Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PENG.png"
    },
    {
      "code": "PENS",
      "name": "Peninsula Specialist College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PENS.png"
    },
    {
      "code": "PHSC",
      "name": "Princes Hill SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PHSC.png"
    },
    {
      "code": "PHXC",
      "name": "Phoenix Community College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PHXC.png"
    },
    {
      "code": "PKDS",
      "name": "Parkdale SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PKDS.png"
    },
    {
      "code": "PRDC",
      "name": "Parade College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PRDC.png"
    },
    {
      "code": "PRSH",
      "name": "Preshil",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PRSH.png"
    },
    {
      "code": "PRVS",
      "name": "Patterson River SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PRVS.png"
    },
    {
      "code": "PSTP",
      "name": "Pleasant Street PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PSTP.png"
    },
    {
      "code": "PTCR",
      "name": "Point Cook Runners",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PTCR.png"
    },
    {
      "code": "PTMS",
      "name": "Port Melbourne SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PTMS.png"
    },
    {
      "code": "PTN",
      "name": "Preston",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PTN.png"
    },
    {
      "code": "PTVC",
      "name": "Plenty Valley Christian Colleg",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/PTVC.png"
    },
    {
      "code": "QLD",
      "name": "Queensland",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/QLD.png"
    },
    {
      "code": "RBDS",
      "name": "Rosebud SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RBDS.png"
    },
    {
      "code": "RCHS",
      "name": "Rochester SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RCHS.png"
    },
    {
      "code": "RDBK",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RDBK.png"
    },
    {
      "code": "REHS",
      "name": "Rosehill SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/REHS.png"
    },
    {
      "code": "RIC",
      "name": "Richmond",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RIC.png"
    },
    {
      "code": "RSBS",
      "name": "Rossbourne School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RSBS.png"
    },
    {
      "code": "RSVH",
      "name": "Reservoir HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RSVH.png"
    },
    {
      "code": "RSWP",
      "name": "Reservoir West PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RSWP.png"
    },
    {
      "code": "RWD",
      "name": "Ringwood",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RWD.png"
    },
    {
      "code": "RWDN",
      "name": "RWD / Nunawading LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RWDN.png"
    },
    {
      "code": "RWVS",
      "name": "Rowville SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RWVS.png"
    },
    {
      "code": "RYGS",
      "name": "Ruyton",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/RYGS.png"
    },
    {
      "code": "SA",
      "name": "South Australia",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SA.png"
    },
    {
      "code": "SACR",
      "name": "Sacre Coeur",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SACR.png"
    },
    {
      "code": "SAN",
      "name": "Sandringham",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SAN.png"
    },
    {
      "code": "SANC",
      "name": "Sandringham College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SANC.png"
    },
    {
      "code": "SBDC",
      "name": "St Bedes College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SBDC.png"
    },
    {
      "code": "SBE",
      "name": "South Bendigo",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SBE.png"
    },
    {
      "code": "SBEK",
      "name": "South Bendigo AV / Kyneton LA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SBEK.png"
    },
    {
      "code": "SBW",
      "name": "South Barwon",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SBW.png"
    },
    {
      "code": "SBYC",
      "name": "Sunbury College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SBYC.png"
    },
    {
      "code": "SCA",
      "name": "South Coast",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SCA.png"
    },
    {
      "code": "SCBC",
      "name": "St Columbas College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SCBC.png"
    },
    {
      "code": "SCOC",
      "name": "Scotch College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SCOC.png"
    },
    {
      "code": "SEDA",
      "name": "SEDA College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SEDA.png"
    },
    {
      "code": "SFCC",
      "name": "St Francis Catholic College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SFCC.png"
    },
    {
      "code": "SFCS",
      "name": "Surf Coast SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SFCS.png"
    },
    {
      "code": "SFOF",
      "name": "St Francis of the Fields",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SFOF.png"
    },
    {
      "code": "SFXC",
      "name": "St Francis Xavier College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SFXC.png"
    },
    {
      "code": "SGP",
      "name": "Singapore",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SGP.png"
    },
    {
      "code": "SHCG",
      "name": "Sacred Heart College Geelong",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SHCG.png"
    },
    {
      "code": "SHCK",
      "name": "Sacred Heart College Kyneton",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SHCK.png"
    },
    {
      "code": "SHCO",
      "name": "Sacred Heart Girls College - O",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SHCO.png"
    },
    {
      "code": "SHLS",
      "name": "St Helena SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SHLS.png"
    },
    {
      "code": "SHPP",
      "name": "Sacred Heart Parish PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SHPP.png"
    },
    {
      "code": "SINC",
      "name": "Siena College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SINC.png"
    },
    {
      "code": "SJFC",
      "name": "St Joseph's College Ferntree Gully",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SJFC.png"
    },
    {
      "code": "SJGC",
      "name": "St Joseph's College Geelong",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SJGC.png"
    },
    {
      "code": "SJSC",
      "name": "St Johns College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SJSC.png"
    },
    {
      "code": "SLCC",
      "name": "Salesian College Chadstone",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SLCC.png"
    },
    {
      "code": "SLSC",
      "name": "Salesian College Sunbury",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SLSC.png"
    },
    {
      "code": "SMBG",
      "name": "St Margarets Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SMBG.png"
    },
    {
      "code": "SME",
      "name": "South Melbourne",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SME.png"
    },
    {
      "code": "SMIG",
      "name": "St Michaels Grammar School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SMIG.png"
    },
    {
      "code": "SMRS",
      "name": "Strathmore SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SMRS.png"
    },
    {
      "code": "SOCG",
      "name": "Southern Cross Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SOCG.png"
    },
    {
      "code": "SPA",
      "name": "Shepparton",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SPA.png"
    },
    {
      "code": "SPAG",
      "name": "St Pauls AGS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SPAG.png"
    },
    {
      "code": "SPTC",
      "name": "St Peters College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SPTC.png"
    },
    {
      "code": "SRTP",
      "name": "Sorrento PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SRTP.png"
    },
    {
      "code": "SSH",
      "name": "St. Stephens Harriers",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SSH.png"
    },
    {
      "code": "STAP",
      "name": "St Alipius PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STAP.png"
    },
    {
      "code": "STBC",
      "name": "St Bernard's College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STBC.png"
    },
    {
      "code": "STBD",
      "name": "St Brigid's College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STBD.png"
    },
    {
      "code": "STCP",
      "name": "St Catherines PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STCP.png"
    },
    {
      "code": "STCS",
      "name": "St Catherine's",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STCS.png"
    },
    {
      "code": "STGG",
      "name": "Strathcona",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STGG.png"
    },
    {
      "code": "STIC",
      "name": "Saint Ignatius College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STIC.png"
    },
    {
      "code": "STJC",
      "name": "St Josephs College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STJC.png"
    },
    {
      "code": "STK",
      "name": "St Kevins",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STK.png"
    },
    {
      "code": "STKC",
      "name": "St Kevin's College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STKC.png"
    },
    {
      "code": "STLC",
      "name": "St Leonard's College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STLC.png"
    },
    {
      "code": "STMA",
      "name": "Santa Maria College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STMA.png"
    },
    {
      "code": "STMC",
      "name": "St Monica's College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STMC.png"
    },
    {
      "code": "STMM",
      "name": "St Mary Mackillop",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STMM.png"
    },
    {
      "code": "STOS",
      "name": "South Oakleigh SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STOS.png"
    },
    {
      "code": "STPC",
      "name": "St Patricks College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STPC.png"
    },
    {
      "code": "STPG",
      "name": "St Patrick's Gordon",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STPG.png"
    },
    {
      "code": "STTM",
      "name": "St Thomas More",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STTM.png"
    },
    {
      "code": "STWC",
      "name": "Saltwater College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/STWC.png"
    },
    {
      "code": "SWNH",
      "name": "Swan Hill College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SWNH.png"
    },
    {
      "code": "SZCH",
      "name": "Suzanne Cory High School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/SZCH.png"
    },
    {
      "code": "TAS",
      "name": "Tasmania",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TAS.png"
    },
    {
      "code": "TBNC",
      "name": "Timboon P-12",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TBNC.png"
    },
    {
      "code": "TBRC",
      "name": "Timbarra P-9",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TBRC.png"
    },
    {
      "code": "TGLC",
      "name": "The Geelong College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TGLC.png"
    },
    {
      "code": "TGNG",
      "name": "The Grange P12",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TGNG.png"
    },
    {
      "code": "THAC",
      "name": "The Hamilton Alexander College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/THAC.png"
    },
    {
      "code": "THBH",
      "name": "Thornbury HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/THBH.png"
    },
    {
      "code": "TKNX",
      "name": "The Knox School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TKNX.png"
    },
    {
      "code": "TLGS",
      "name": "Tallangatta SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TLGS.png"
    },
    {
      "code": "TMCC",
      "name": "Thomas Carr College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TMCC.png"
    },
    {
      "code": "TMPC",
      "name": "Templestowe College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TMPC.png"
    },
    {
      "code": "TRH",
      "name": "Traralgon",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TRH.png"
    },
    {
      "code": "TRI",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TRI.png"
    },
    {
      "code": "TRKC",
      "name": "Toorak College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TRKC.png"
    },
    {
      "code": "TRNC",
      "name": "Trinity Anglican College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TRNC.png"
    },
    {
      "code": "TRNG",
      "name": "Trinity Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TRNG.png"
    },
    {
      "code": "TTNG",
      "name": "Tintern Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TTNG.png"
    },
    {
      "code": "TXRR",
      "name": "TXR Runners",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/TXRR.png"
    },
    {
      "code": "UNIH",
      "name": "University HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/UNIH.png"
    },
    {
      "code": "USA",
      "name": "USA",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/USA.png"
    },
    {
      "code": "VBKS",
      "name": "Viewbank SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VBKS.png"
    },
    {
      "code": "VCCL",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VCCL.png"
    },
    {
      "code": "VCL",
      "name": "Vic Cross Country",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VCL.png"
    },
    {
      "code": "VIC",
      "name": "Victoria",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VIC.png"
    },
    {
      "code": "VMA",
      "name": "Victorian Masters Athletics",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VMA.png"
    },
    {
      "code": "VMTS",
      "name": "Vermont SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VMTS.png"
    },
    {
      "code": "VRQA",
      "name": "Home School",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VRQA.png"
    },
    {
      "code": "VRWC",
      "name": "Victorian Race Walking Club",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VRWC.png"
    },
    {
      "code": "VTCC",
      "name": "Victory Christian college",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VTCC.png"
    },
    {
      "code": "VUT",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/VUT.png"
    },
    {
      "code": "WA",
      "name": "Western Australia",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WA.png"
    },
    {
      "code": "WAM",
      "name": "Waverley-Malvern",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WAM.png"
    },
    {
      "code": "WBEG",
      "name": "Westbourne Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WBEG.png"
    },
    {
      "code": "WCA",
      "name": "Whittlesea",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WCA.png"
    },
    {
      "code": "WCY",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WCY.png"
    },
    {
      "code": "WDMC",
      "name": "Wodonga Middle Years College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WDMC.png"
    },
    {
      "code": "WDSC",
      "name": "Wodonga Senior SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WDSC.png"
    },
    {
      "code": "WDSS",
      "name": "Wangaratta District Specialist",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WDSS.png"
    },
    {
      "code": "WEL",
      "name": "Wellington",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WEL.png"
    },
    {
      "code": "WELA",
      "name": "WEL",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WELA.png"
    },
    {
      "code": "WEN",
      "name": "Wendouree",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WEN.png"
    },
    {
      "code": "WENA",
      "name": "WEN",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WENA.png"
    },
    {
      "code": "WES",
      "name": "Western Athletics",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WES.png"
    },
    {
      "code": "WESC",
      "name": "Wesley College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WESC.png"
    },
    {
      "code": "WHFC",
      "name": "Whitefriars College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WHFC.png"
    },
    {
      "code": "WLNS",
      "name": "Wallan Secondary College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WLNS.png"
    },
    {
      "code": "WNBC",
      "name": "Warrnambool College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WNBC.png"
    },
    {
      "code": "WNDP",
      "name": "Wendouree PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WNDP.png"
    },
    {
      "code": "WNTC",
      "name": "Wantirna College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WNTC.png"
    },
    {
      "code": "WOD",
      "name": "Wodonga",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WOD.png"
    },
    {
      "code": "WODEN",
      "name": "Woden",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WODEN.png"
    },
    {
      "code": "WRBS",
      "name": "Werribee Secondary",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WRBS.png"
    },
    {
      "code": "WSHC",
      "name": "Western Heights College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WSHC.png"
    },
    {
      "code": "WTHS",
      "name": "Williamstown HS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WTHS.png"
    },
    {
      "code": "WTN",
      "name": "Williamstown",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WTN.png"
    },
    {
      "code": "WVCC",
      "name": "Waverley Christian",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WVCC.png"
    },
    {
      "code": "WYN",
      "name": "Wyndham",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/WYN.png"
    },
    {
      "code": "XAV",
      "name": null,
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/XAV.png"
    },
    {
      "code": "XAVC",
      "name": "Xavier College",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/XAVC.png"
    },
    {
      "code": "YMBP",
      "name": "Yarrambat PS",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/YMBP.png"
    },
    {
      "code": "YRA",
      "name": "Yarra Ranges",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/YRA.png"
    },
    {
      "code": "YRMS",
      "name": "Yarram SC",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/YRMS.png"
    },
    {
      "code": "YRVG",
      "name": "Yarra Valley Grammar",
      "logoUrl": "https://athsvic.resultshub.com.au/graphics/clubs/YRVG.png"
    }
] as const
